      // Le niveau désigne qui peut agir ou décider ; le contexte précise les faits
      // et contraintes à examiner. Cette taxonomie éditoriale reste à tester avec
      // les personnes qui utilisent l'outil. Les scènes sont fictives.
      const contextCatalog = {
        personal: {
          daily: {
            label: "Quotidien et démarches",
            description: "Une tâche, un papier ou une démarche à organiser.",
            focus: "Quelle tâche concrète est bloquée, et pour quand ?",
            caution: "Une petite action peut aider à commencer sans supprimer les contraintes autour de moi.",
            prompts: [
              "Quel fait précis montre que la tâche bloque ? Y a-t-il une échéance ?",
              "Quel résultat limité me serait utile maintenant ?",
              "Qu'est-ce qui manque pour faire le premier morceau ?",
            ],
            examples: {
              situation: "Je ne retrouve pas deux factures à régler cette semaine parmi mes courriers.",
              goal: "Retrouver les factures ou demander une copie avant vendredi.",
              obstacle: "Les courriers sont mélangés et je ne sais pas lesquels ouvrir d'abord.",
              ideas: ["Trier les courriers reçus ce mois-ci.", "Demander une copie à l'organisme concerné.", "Demander dix minutes d'aide à une personne de confiance."],
              comparison: ["Je peux commencer par une petite pile de courriers.", "Le tri seul peut ne pas retrouver une facture ancienne."],
              action: "Ouvrir les cinq courriers les plus récents demain matin pendant dix minutes.",
              measure: "J'ai trouvé une facture ou identifié l'organisme à contacter.",
              result: "J'ai retrouvé une facture et demandé une copie de la seconde.",
              support: "Une personne de confiance peut m'aider à repérer les échéances.",
              backup: "Si je me sens débordé, j'ouvre une seule enveloppe puis je fais une pause.",
              control: "Choisir par quels courriers commencer et demander une copie.",
              outside: "Le délai de réponse de l'organisme.",
            },
            tool: ["Découper un problème pratique", "Décrire la tâche, choisir une action faisable et vérifier ce qui s'est passé. L'approche PM+ est accompagnée par des personnes formées ; ce site n'est pas PM+.", "#ref-3"],
          },
          study: {
            label: "Étudier ou apprendre",
            description: "Une consigne, un travail ou une façon d'apprendre.",
            focus: "Quelle consigne dois-je transformer en premier livrable ?",
            caution: "Les résultats de la recherche scolaire ne garantissent pas le même effet pour chaque âge ou situation.",
            prompts: [
              "Quel travail est demandé, et quelle partie de la consigne est floue ?",
              "Quel premier résultat vérifiable puis-je produire ?",
              "Qu'est-ce qui m'empêche de commencer ou de vérifier mon travail ?",
            ],
            examples: {
              situation: "Je dois rendre un dossier la semaine prochaine et je n'ai pas commencé son plan.",
              goal: "Écrire un plan provisoire de trois titres aujourd'hui.",
              obstacle: "Je veux tout lire avant d'écrire et une partie de la consigne reste floue.",
              ideas: ["Faire un plan provisoire sans chercher la perfection.", "Noter une question précise à poser à l'enseignant.", "Expliquer mon idée à un camarade pour voir ce qui manque."],
              comparison: ["Un brouillon rend visible ce que je comprends déjà.", "Je devrai peut-être le revoir après une précision sur la consigne."],
              action: "Relire la consigne et écrire trois titres pendant quinze minutes.",
              measure: "J'ai trois titres provisoires et une question claire si besoin.",
              result: "J'ai rédigé deux titres et identifié une question à poser.",
              support: "La consigne, un enseignant ou un camarade disponible.",
              backup: "Si je bloque, je note une seule question puis je demande un retour.",
              control: "Faire un brouillon et formuler une question.",
              outside: "Le délai de réponse de l'enseignant.",
            },
            tool: ["Planifier, vérifier, ajuster", "Je prévois une façon d'aborder le travail, j'observe ce que j'ai compris, puis j'ajuste. Ces repères viennent surtout d'études en milieu scolaire.", "#ref-31"],
          },
          work: {
            label: "Ma charge de travail",
            description: "Des tâches ou délais qui se heurtent dans mon travail.",
            focus: "Quelles tâches se concurrencent, et qui fixe leur priorité ?",
            caution: "Je peux demander un arbitrage ; je ne suis pas seul responsable des moyens et des délais imposés.",
            prompts: [
              "Quelles demandes sont arrivées, par qui, et avec quelles échéances ?",
              "Quelle priorité ou quel délai réaliste faudrait-il clarifier ?",
              "Quelle décision dépasse ma marge de manœuvre ?",
            ],
            examples: {
              situation: "Deux responsables m'ont confié trois dossiers urgents à finir le même jour.",
              goal: "Obtenir un ordre de priorité et un délai réaliste pour chaque dossier.",
              obstacle: "Les responsables n'ont pas arbitré ensemble et le temps disponible est limité.",
              ideas: ["Lister les tâches et le temps estimé pour chacune.", "Demander un arbitrage écrit des priorités.", "Demander l'appui d'un collègue ou d'un représentant du personnel."],
              comparison: ["Une liste factuelle peut rendre le conflit de délais visible.", "La décision finale dépend des responsables."],
              action: "Préparer la liste des trois dossiers et demander quel travail traiter d'abord.",
              measure: "Une priorité est confirmée ou un rendez-vous d'arbitrage est fixé.",
              result: "Deux priorités ont été clarifiées ; le troisième délai reste à discuter.",
              support: "Un collègue de confiance ou un représentant du personnel.",
              backup: "Si le responsable est absent, j'envoie la liste et demande un moment de décision.",
              control: "Décrire les tâches et demander une décision sur leur ordre.",
              outside: "Les effectifs, les échéances imposées et l'arbitrage final.",
            },
            tool: ["Séparer faits et marge de manœuvre", "Je décris les demandes vérifiables puis cherche une action possible sans me rendre responsable de décisions qui dépendent de l'organisation.", "#ref-3"],
          },
          health: {
            label: "Accéder à un soin ou à une aide",
            description: "Un obstacle pour obtenir un rendez-vous ou une information.",
            focus: "Qu'est-ce qui m'empêche d'accéder au soin ou à l'aide souhaitée ?",
            caution: "Cet exercice aide à préparer une demande ; il ne choisit pas un traitement et ne remplace pas un professionnel.",
            prompts: [
              "Quel rendez-vous, soin ou soutien est difficile d'accès ?",
              "Quelle information ou possibilité concrète voudrais-je obtenir ?",
              "L'obstacle est-il le trajet, le coût, l'horaire, la compréhension ou autre chose ?",
            ],
            examples: {
              situation: "J'ai manqué deux rendez-vous car le trajet jusqu'au cabinet est difficile à organiser.",
              goal: "Préparer une solution de déplacement pour le prochain rendez-vous.",
              obstacle: "Je ne connais pas les aides possibles et je ne peux pas compter sur un accompagnement régulier.",
              ideas: ["Demander au secrétariat les horaires possibles.", "Demander si une autre modalité convient à ce soin.", "Chercher une aide au transport avec un intervenant social."],
              comparison: ["Contacter l'équipe peut clarifier les possibilités réelles.", "Une autre modalité peut ne pas convenir au soin prévu."],
              action: "Contacter le secrétariat pour expliquer l'obstacle de transport.",
              measure: "J'ai une option de déplacement ou une proposition convenue avec l'équipe.",
              result: "Un autre horaire a été proposé ; le transport reste à confirmer.",
              support: "Un proche ou un intervenant social, si je souhaite son aide.",
              backup: "Si téléphoner est difficile, je prépare un court message à envoyer.",
              control: "Expliquer l'obstacle et poser mes questions.",
              outside: "Les disponibilités et les options de soin réellement adaptées.",
            },
            tool: ["Préparer mes questions pour le soin", "J'identifie l'obstacle d'accès et les informations dont j'ai besoin pour participer à la décision avec l'équipe de soins.", "#ref-30"],
          },
          boundaries: {
            label: "Mes limites dans une relation",
            description: "Un choix personnel qui ne dépend pas d'un accord à deux.",
            focus: "Quelle limite ai-je besoin de poser, et est-ce sûr de le faire ?",
            caution: "En cas de peur, de menace ou de contrôle, je cherche un soutien sûr avant toute confrontation.",
            prompts: [
              "Quel comportement concret me gêne ou réduit ma liberté ?",
              "Quelle limite ou quel soutien me serait utile à moi ?",
              "Qu'est-ce qui rend cette limite difficile ou dangereuse à exprimer ?",
            ],
            examples: {
              situation: "Mon partenaire me demande de lui montrer mes messages personnels chaque soir.",
              goal: "Trouver un soutien sûr pour réfléchir à ma vie privée et à ma sécurité.",
              obstacle: "Je crains sa réaction si je refuse directement.",
              ideas: ["Parler à une personne de confiance hors de sa présence.", "Consulter les repères de sécurité et les possibilités d'aide.", "Préparer une manière sûre de conserver des informations utiles pour moi."],
              comparison: ["Un échange confidentiel peut m'aider à clarifier mes choix.", "Une confrontation immédiate pourrait augmenter le risque si j'ai peur."],
              action: "Choisir un moment sûr pour contacter une personne de confiance.",
              measure: "J'ai identifié un soutien et une prochaine démarche qui ne m'expose pas davantage.",
              result: "J'ai parlé à une personne sûre et décidé de chercher un avis spécialisé.",
              support: "Une personne de confiance ou un service spécialisé.",
              backup: "Si contacter quelqu'un n'est pas sûr maintenant, je cherche un autre moment ou canal sûr.",
              control: "Choisir à qui parler et quelles informations partager, quand c'est sûr.",
              outside: "Le comportement de l'autre personne et sa réaction.",
            },
            tool: ["Sécurité avant discussion", "La peur, le contrôle ou les menaces demandent un soutien adapté. Un accord obtenu sous pression n'est pas libre.", "#ref-6"],
          },
          other: {
            label: "Autre situation personnelle",
            description: "Mon problème ne ressemble pas aux exemples proposés.",
            focus: "Quel fait précis aimerais-je comprendre ou changer ?",
            caution: "Je peux demander un soutien adapté si la situation dépasse ce que je peux régler seul.",
            prompts: ["Que s'est-il passé récemment, de façon observable ?", "Quel petit changement me serait utile ?", "Qu'est-ce qui manque pour avancer ?"],
            examples: {
              situation: "Une demande importante attend ma réponse depuis plusieurs jours.",
              goal: "Comprendre ce qui est attendu et préparer une réponse avant vendredi.",
              obstacle: "Je ne sais pas quelle information vérifier en premier.",
              ideas: ["Relire la demande et surligner les questions.", "Demander une précision à son auteur.", "Demander un appui à une personne de confiance."],
              comparison: ["Une question précise peut lever une incertitude.", "La réponse peut prendre du temps."],
              action: "Relire la demande pendant dix minutes et noter une question.",
              measure: "J'ai une question précise ou une première réponse écrite.",
              result: "J'ai identifié l'information manquante et demandé une précision.",
              support: "Une personne de confiance ou un service adapté au sujet.",
              backup: "Si je bloque, je commence par une seule phrase.",
              control: "Demander une précision et préparer ma réponse.",
              outside: "Le délai et la réponse de l'autre partie.",
            },
            tool: ["Définir un problème concret", "Je distingue un fait, un résultat souhaité et un obstacle avant d'essayer une piste. Il s'agit d'un repère pratique, pas d'un diagnostic.", "#ref-3"],
          },
        },
        shared: {
          couple: {
            label: "Couple ou relation proche",
            description: "Une décision commune possible si chacun peut refuser librement.",
            focus: "Quel sujet pouvons-nous discuter sans pression ni peur ?",
            caution: "Si je crains une réaction, l'accord à deux n'est pas le bon point de départ : je cherche d'abord une aide sûre.",
            prompts: ["Quel fait chacun peut-il décrire sans attribuer d'intention ?", "Quel changement puis-je proposer sans décider pour l'autre ?", "Que ne savons-nous pas encore des besoins ou limites de chacun ?"],
            examples: {
              situation: "Nous avons annulé deux moments ensemble car nos horaires n'étaient pas coordonnés.",
              goal: "Trouver un créneau qui convient aux deux personnes, si nous le souhaitons.",
              obstacle: "Nous n'avons pas comparé nos disponibilités ni demandé ce qui est important pour chacun.",
              ideas: ["Proposer un échange calme de quinze minutes.", "Comparer deux créneaux possibles.", "Prévoir une activité plus courte si cela convient aux deux."],
              comparison: ["Chacun peut dire ce qui lui convient.", "L'autre personne peut refuser le créneau proposé."],
              action: "Demander si un moment pour parler des disponibilités conviendrait.",
              measure: "Chacun a pu exprimer son choix, même si aucun créneau n'est encore fixé.",
              result: "Nous avons retenu une promenade courte ; le calendrier partagé ne nous convient pas.",
              support: "Un moment calme et, si besoin, un tiers choisi librement par chacun.",
              backup: "Si la discussion ne convient pas, je la reporte sans insister.",
              control: "Formuler mon besoin et écouter la réponse.",
              outside: "La disponibilité et le consentement de l'autre personne.",
            },
            tool: ["Écouter et vérifier l'accord", "Je demande le point de vue de l'autre, le reformule et vérifie qu'un refus est possible. En présence de violence, la sécurité prime.", "#ref-5"],
          },
          family: {
            label: "Dans la famille",
            description: "Une organisation familiale qui touche plusieurs personnes.",
            focus: "Qui est concerné, et que peut décider chaque personne selon son rôle et son âge ?",
            caution: "Un enfant doit pouvoir être entendu, sans porter une décision qui relève des adultes.",
            prompts: ["À quel moment la difficulté apparaît-elle et pour qui ?", "Quel changement serait utile à la famille, sans imposer un accord fictif ?", "Quelles contraintes ou besoins n'ont pas encore été entendus ?"],
            examples: {
              situation: "Le départ du matin est tendu et mon enfant et moi arrivons souvent en retard.",
              goal: "Essayer deux matins plus calmes cette semaine.",
              obstacle: "Les affaires ne sont pas prêtes et nous n'avons pas demandé ce qui est difficile pour chacun.",
              ideas: ["Préparer les sacs ensemble la veille.", "Dessiner une routine courte avec l'enfant.", "Retirer une tâche non indispensable du matin."],
              comparison: ["L'enfant peut montrer ce qui l'aide à se préparer.", "Une routine trop stricte ne tiendra pas face à la fatigue ou aux imprévus."],
              action: "Demander à l'enfant ce qui bloque le matin et préparer le sac ensemble ce soir.",
              measure: "Une étape du départ est plus simple pour chacun.",
              result: "Le sac était prêt ; le petit-déjeuner demande encore du temps.",
              support: "Un autre adulte sûr, si la famille le souhaite.",
              backup: "Si l'enfant est fatigué, nous préparons seulement l'essentiel.",
              control: "Proposer une routine adaptée et écouter l'enfant.",
              outside: "Le sommeil, les imprévus et les contraintes des autres adultes.",
            },
            tool: ["Écouter chaque besoin sans juger", "Je demande ce que chacun vit, puis j'adapte l'essai aux possibilités réelles de la famille. Le guide OMS soutient l'écoute et les besoins pratiques, pas une méthode familiale validée ici.", "#ref-5"],
          },
          colleague: {
            label: "Collègues ou formation",
            description: "Une difficulté entre personnes au travail ou en apprentissage.",
            focus: "Les personnes peuvent-elles parler librement malgré leurs rôles différents ?",
            caution: "Une différence d'autorité ou la peur de représailles peut rendre une discussion directe inadaptée.",
            prompts: ["Qu'a dit ou fait chaque personne, sans supposer son intention ?", "Quelle écoute ou clarification voudrais-je proposer ?", "Quel rôle, pouvoir ou risque rend la discussion difficile ?"],
            examples: {
              situation: "Un médecin expérimenté compare souvent la difficulté d'un jeune collègue à ce qu'il a vécu autrefois.",
              goal: "Que le jeune collègue puisse expliquer son problème avant de recevoir un conseil.",
              obstacle: "Le médecin expérimenté pense aider, mais les comparaisons interrompent le récit et fragilisent la confiance.",
              ideas: ["Demander au jeune collègue ce dont il a besoin maintenant.", "Proposer au médecin expérimenté d'écouter puis de reformuler avant de conseiller.", "Prévoir un tiers sûr si la hiérarchie rend l'échange difficile."],
              comparison: ["La reformulation peut vérifier que le problème est compris.", "Un échange direct peut être difficile si la personne senior évalue le jeune collègue."],
              action: "Demander au jeune collègue s'il souhaite un échange avec le médecin ou un autre soutien.",
              measure: "Le jeune collègue a pu exprimer sa difficulté sans être interrompu, ou a choisi un autre canal.",
              result: "Le jeune collègue a décrit son besoin ; il préfère un prochain échange avec un autre référent.",
              support: "Un référent pédagogique ou un tiers choisi librement.",
              backup: "Si l'échange n'est pas sûr, demander un autre canal de soutien.",
              control: "Écouter, reformuler et proposer un choix de soutien.",
              outside: "L'avis du collègue et les décisions de la hiérarchie.",
            },
            tool: ["Écouter avant de conseiller", "Je demande quel retour serait utile, reformule la difficulté, puis vérifie si un conseil est souhaité. Les études de retours en formation clinique éclairent la confiance sans valider ce parcours ni effacer une asymétrie de pouvoir.", "#ref-18"],
          },
          neighbors: {
            label: "Voisins ou association",
            description: "Une règle ou une ressource partagée à discuter.",
            focus: "Quelle ressource partageons-nous et quel essai chacun peut-il accepter ?",
            caution: "Je ne parle pas au nom du groupe sans son accord et je vérifie les règles déjà applicables.",
            prompts: ["Quel usage partagé pose problème, et à quels moments ?", "Quel accord limité pourrions-nous essayer ?", "Qui n'a pas encore été entendu ou pourrait être pénalisé ?"],
            examples: {
              situation: "Deux associations souhaitent utiliser la même salle le jeudi soir.",
              goal: "Trouver un essai de calendrier acceptable pour les deux associations.",
              obstacle: "Nous ne connaissons pas les contraintes de transport et d'horaire de chaque groupe.",
              ideas: ["Demander les contraintes de chaque association.", "Tester une alternance pendant un mois.", "Chercher un autre créneau avec le gestionnaire de la salle."],
              comparison: ["Un essai limité peut révéler les contraintes réelles.", "Une alternance peut exclure des membres indisponibles une semaine sur deux."],
              action: "Inviter chaque association à nommer ses contraintes avant de proposer un calendrier.",
              measure: "Chaque groupe a pu répondre et un essai est accepté ou modifié.",
              result: "Les groupes ont trouvé un créneau d'essai ; le transport du second groupe reste à vérifier.",
              support: "Le gestionnaire de la salle, si les groupes souhaitent son aide.",
              backup: "Si aucune alternance ne convient, chercher un autre lieu ou horaire.",
              control: "Demander les besoins et proposer un essai réversible.",
              outside: "Les disponibilités du lieu et l'accord des autres membres.",
            },
            tool: ["Essai d'accord réversible", "Je propose une règle limitée dans le temps, puis je demande à chaque groupe si elle fonctionne. Cette pratique est une adaptation de principes d'écoute et de participation.", "#ref-25"],
          },
          other: {
            label: "Autre situation entre personnes",
            description: "Un sujet à discuter avec une autre personne, si c'est sûr.",
            focus: "Qu'est-ce que chacun peut décider librement ?",
            caution: "S'il y a peur ou contrôle, je privilégie un soutien sûr plutôt qu'une négociation.",
            prompts: ["Quel fait concret est à discuter ?", "Quelle proposition respecte la liberté de chacun ?", "Quelle information ou limite manque encore ?"],
            examples: {
              situation: "Nous avons pris des décisions différentes sur une tâche commune.",
              goal: "Clarifier ce que chacun souhaite faire et choisir un petit essai.",
              obstacle: "Nous n'avons pas encore expliqué nos contraintes respectives.",
              ideas: ["Demander le point de vue de chacun.", "Écrire deux propositions à discuter.", "Faire appel à un tiers choisi ensemble."],
              comparison: ["Chacun peut préciser ses limites.", "Aucune proposition ne doit être présentée comme déjà acceptée."],
              action: "Proposer un court échange pour écouter les contraintes de chacun.",
              measure: "Les accords et les désaccords sont nommés clairement.",
              result: "Nous avons identifié une étape commune et un point encore à discuter.",
              support: "Un tiers sûr choisi librement.",
              backup: "Si le moment ne convient pas, reporter ou choisir un autre canal.",
              control: "Exprimer mon besoin et écouter une réponse.",
              outside: "Le consentement et les choix de l'autre personne.",
            },
            tool: ["Reformuler avant de proposer", "Je vérifie que j'ai compris l'autre personne avant de suggérer une solution. L'écoute aide à clarifier, sans garantir un accord.", "#ref-5"],
          },
        },
        organization: {
          coordination: {
            label: "Priorités et coordination",
            description: "Le travail se bloque entre rôles, étapes ou équipes.",
            focus: "À quelle étape le travail se bloque-t-il, et qui peut arbitrer ?",
            caution: "Une amélioration doit être examinée avec les personnes qui font le travail et celles qu'elle touche.",
            prompts: ["Où, quand et pour qui le blocage se répète-t-il ?", "Quel résultat l'équipe veut-elle obtenir ?", "Quelle règle, décision ou ressource manque selon les faits disponibles ?"],
            examples: {
              situation: "Trois demandes urgentes arrivent chaque lundi sans règle de priorité commune.",
              goal: "Que l'équipe sache quelle demande traiter d'abord et qui arbitre.",
              obstacle: "Plusieurs responsables donnent des consignes séparées et les priorités ne sont pas visibles.",
              ideas: ["Dessiner le circuit actuel d'une demande avec l'équipe.", "Tester une règle de priorité lors d'une réunion.", "Nommer un responsable d'arbitrage pour un essai limité."],
              comparison: ["Un test limité peut montrer si la règle clarifie le travail.", "Il peut déplacer le retard vers une autre tâche."],
              action: "Proposer au responsable un test de priorisation sur une seule réunion.",
              measure: "Les demandes reçoivent un ordre connu de l'équipe sans accroître un autre retard.",
              result: "Les priorités ont été clarifiées ; un retard imprévu est apparu sur une autre tâche.",
              support: "Les personnes qui reçoivent les demandes et un responsable habilité.",
              backup: "Si le test crée un nouveau retard, l'équipe revoit la règle avant de l'étendre.",
              control: "Décrire le circuit et proposer un test avec autorisation.",
              outside: "L'arbitrage final, les effectifs et certaines échéances.",
            },
            tool: ["Petit test et mesure d'équilibrage", "L'équipe précise son but, teste un changement à petite échelle et regarde aussi les effets indésirables avant de l'étendre.", "#ref-22"],
          },
          service: {
            label: "Accès et qualité d'un service",
            description: "Des usagers rencontrent un obstacle dans un parcours.",
            focus: "Qui n'arrive pas à utiliser le service, et à quelle étape ?",
            caution: "Les hypothèses de l'équipe doivent être vérifiées avec des usagers divers, y compris ceux qui renoncent.",
            prompts: ["À quelle étape du service des personnes échouent-elles ou abandonnent-elles ?", "Qu'est-ce qui devrait devenir plus accessible pour elles ?", "Que savons-nous par les usagers, et que supposons-nous encore ?"],
            examples: {
              situation: "Les rendez-vous ne se prennent qu'en ligne ; plusieurs usagers quittent le parcours avant confirmation.",
              goal: "Permettre à davantage de personnes de confirmer un rendez-vous par un canal utilisable.",
              obstacle: "L'équipe connaît peu les raisons des abandons et aucun autre canal n'est affiché.",
              ideas: ["Observer le parcours avec des usagers volontaires.", "Tester une consigne plus claire sur la première page.", "Étudier un autre canal de réservation avec les équipes concernées."],
              comparison: ["Observer les usages réels peut corriger une hypothèse de l'équipe.", "Une seule amélioration d'écran peut laisser l'obstacle d'accès intact."],
              action: "Demander à quelques usagers volontaires où ils s'arrêtent dans la prise de rendez-vous.",
              measure: "L'équipe identifie les obstacles et suit les rendez-vous effectivement confirmés selon le canal.",
              result: "Les usagers ont signalé un code de confirmation difficile à recevoir ; le test doit être revu.",
              support: "Des usagers volontaires et les personnes qui assurent l'accueil.",
              backup: "Si l'observation est impossible, examiner les demandes d'aide déjà reçues puis vérifier les hypothèses.",
              control: "Organiser une recherche consentie et proposer un changement limité.",
              outside: "Le budget, les systèmes et la décision d'ouvrir un autre canal.",
            },
            tool: ["Observer les besoins réels", "Je cherche qui utilise ou quitte le service, ce que ces personnes veulent accomplir et ce qui les empêche d'y parvenir.", "#ref-28"],
          },
          conditions: {
            label: "Conditions de travail et sécurité",
            description: "Un risque, une violence ou une condition de travail à traiter.",
            focus: "Quel risque est observé et quel canal de signalement est sûr ?",
            caution: "Une violence ou un harcèlement ne se règle pas par une médiation imposée ; les droits et procédures dépendent du lieu.",
            prompts: ["Quels faits, lieux et moments rendent le travail difficile ou dangereux ?", "Quel changement de condition ou de protection est recherché ?", "Qui peut agir sans exposer les personnes à des représailles ?"],
            examples: {
              situation: "Des incidents lors des fermetures tardives ne sont pas transmis à l'équipe suivante.",
              goal: "Mettre en place une transmission sûre des incidents et décider d'une mesure de protection.",
              obstacle: "Le canal actuel n'est pas clair et des salariés craignent d'être identifiés.",
              ideas: ["Clarifier qui reçoit les signalements et comment les protéger.", "Examiner les faits avec les représentants du personnel.", "Tester une transmission minimale sans données personnelles inutiles."],
              comparison: ["Un canal clair peut permettre d'agir sur un risque documenté.", "Un formulaire mal conçu peut exposer une personne ou réduire les signalements."],
              action: "Demander à l'instance compétente comment signaler les incidents sans exposer les salariés.",
              measure: "Un canal sûr est connu et une mesure de protection est discutée avec les personnes concernées.",
              result: "Un canal a été précisé ; la protection lors des fermetures reste à décider.",
              support: "Représentants du personnel et service compétent en prévention.",
              backup: "Si le canal interne n'est pas sûr, chercher un conseil indépendant adapté au lieu.",
              control: "Décrire le risque et vérifier les voies de signalement.",
              outside: "Les décisions de l'employeur et les procédures applicables.",
            },
            tool: ["Prévenir sans exposer", "Les repères de l'OIT invitent à prévenir les violences et à prévoir des voies de recours adaptées. Le droit concret varie selon le pays et l'organisation.", "#ref-29"],
          },
          change: {
            label: "Tester un changement",
            description: "Une nouvelle façon de travailler a besoin d'être évaluée.",
            focus: "Quel résultat attendons-nous, pour qui, et quel effet secondaire surveiller ?",
            caution: "Un test local renseigne sur ce contexte ; il ne prouve pas à lui seul qu'un changement fonctionnera partout.",
            prompts: ["Quel problème justifie le changement proposé ?", "Quel résultat observable veulent les personnes concernées ?", "Quelles hypothèses, contraintes ou conséquences involontaires faut-il vérifier ?"],
            examples: {
              situation: "Une nouvelle réunion de suivi a été ajoutée, mais les demandes prennent plus de temps à être traitées.",
              goal: "Garder une coordination utile sans allonger le délai des demandes.",
              obstacle: "La réunion répète des informations déjà saisies et son effet n'a pas été mesuré.",
              ideas: ["Demander à l'équipe quelles décisions exigent réellement une réunion.", "Tester un ordre du jour limité pendant deux semaines.", "Supprimer les points doublons et comparer les délais."],
              comparison: ["Un essai court permet d'observer une différence locale.", "Réduire la réunion peut faire manquer une information importante."],
              action: "Faire valider un test de deux réunions avec un ordre du jour limité.",
              measure: "Le temps de réunion baisse sans hausse des demandes oubliées.",
              result: "La réunion a été plus courte ; une demande oubliée impose d'ajuster le suivi.",
              support: "Les personnes qui utilisent les informations et un responsable du test.",
              backup: "Si une demande passe inaperçue, réintroduire le point nécessaire.",
              control: "Définir un test, ses mesures et les personnes à consulter.",
              outside: "La décision de maintenir ou déployer le changement.",
            },
            tool: ["But, mesures, test, ajustement", "Je précise ce que l'équipe veut accomplir, comment elle le saura et quel petit changement elle peut tester. Je vérifie les effets non prévus.", "#ref-22"],
          },
          other: {
            label: "Autre situation dans une organisation",
            description: "Un problème lié à des règles, des ressources ou un processus.",
            focus: "Quel résultat le système produit-il et qui peut décider d'un changement ?",
            caution: "Je vérifie les faits avec les personnes concernées avant d'attribuer le problème à une personne.",
            prompts: ["Où le problème apparaît-il et qui en subit les effets ?", "Quel résultat améliorerait la situation pour ces personnes ?", "Quelle règle, ressource ou coordination manque ?"],
            examples: {
              situation: "Plusieurs demandes reviennent à l'équipe faute d'une consigne commune.",
              goal: "Réduire les retours inutiles sans compliquer la demande initiale.",
              obstacle: "La consigne varie selon la personne qui répond.",
              ideas: ["Comparer quelques cas de retour avec l'équipe.", "Écrire une consigne provisoire commune.", "Tester la consigne sur une semaine puis recueillir les retours."],
              comparison: ["Une consigne commune peut réduire les hésitations.", "Elle peut être trop rigide pour certains cas."],
              action: "Proposer un test d'une semaine avec une consigne provisoire validée.",
              measure: "Moins de demandes reviennent, sans augmentation des erreurs.",
              result: "Les retours ont diminué dans les cas simples ; les exceptions restent à préciser.",
              support: "L'équipe et la personne habilitée à valider le test.",
              backup: "Si des erreurs apparaissent, arrêter le test et ajuster la consigne.",
              control: "Documenter les cas et proposer une vérification limitée.",
              outside: "La validation et les moyens de l'organisation.",
            },
            tool: ["Tester avant de généraliser", "Un petit test documenté aide l'équipe à apprendre du contexte et des effets inattendus avant une mise en œuvre plus large.", "#ref-22"],
          },
        },
        public: {
          mobility: {
            label: "Mobilité et espace public",
            description: "Un lieu ou un transport collectif difficile d'accès.",
            focus: "Qui ne peut utiliser quel espace ou transport, et qui décide des aménagements ?",
            caution: "Je demande l'accord avant de rapporter l'expérience d'une autre personne et je n'affirme pas représenter tout le quartier.",
            prompts: ["Quel lieu précis pose problème, pour qui et à quel moment ?", "Quelle décision ou réponse publique est recherchée ?", "Quelles observations et quel responsable manquent encore ?"],
            examples: {
              situation: "L'arrêt de bus du quartier est difficile d'accès pour plusieurs habitants ; aucun calendrier de travaux n'est publié.",
              goal: "Obtenir une réponse du service compétent sur les aménagements possibles.",
              obstacle: "Nous ne savons pas qui décide et quelles personnes souhaitent participer.",
              ideas: ["Recueillir des observations avec l'accord des personnes concernées.", "Identifier l'autorité compétente et les informations publiques.", "Préparer une demande collective précise."],
              comparison: ["Une demande documentée peut obtenir une réponse vérifiable.", "Une réponse ne garantit pas les travaux ni leur financement."],
              action: "Identifier le service responsable et demander aux habitants intéressés ce qu'ils souhaitent partager.",
              measure: "Le service répond ou indique un calendrier de décision.",
              result: "Le service responsable a été identifié ; une rencontre reste à demander.",
              support: "Des habitants volontaires et une association locale.",
              backup: "Si l'interlocuteur est inconnu, demander une orientation à la collectivité.",
              control: "Réunir des faits publics et formuler une demande avec les volontaires.",
              outside: "Le budget, les travaux et la décision de l'autorité.",
            },
            tool: ["Demande publique vérifiable", "Je précise le lieu, les personnes touchées, l'autorité compétente et la réponse attendue. La participation doit pouvoir influencer une décision réelle.", "#ref-25"],
          },
          rights: {
            label: "Service public et accès aux droits",
            description: "Une démarche publique exclut ou décourage des personnes.",
            focus: "À quelle étape des personnes renoncent-elles à une démarche publique ?",
            caution: "Les règles d'éligibilité et les recours relèvent du droit applicable ; l'outil aide à formuler le problème, pas à trancher un droit.",
            prompts: ["Quelle démarche bloque, et quelles personnes sont touchées ?", "Quel accès ou changement de service demander précisément ?", "Quelles règles et raisons d'abandon restent à vérifier ?"],
            examples: {
              situation: "Une démarche locale se fait seulement en ligne ; certaines personnes abandonnent avant d'obtenir une réponse.",
              goal: "Demander qu'une voie utilisable soit proposée aux personnes qui ne peuvent terminer en ligne.",
              obstacle: "Nous ne connaissons ni les causes précises d'abandon ni le service qui décide du canal d'accès.",
              ideas: ["Demander aux usagers volontaires à quelle étape ils bloquent.", "Consulter les informations publiques sur les voies existantes.", "Adresser une demande documentée au service compétent."],
              comparison: ["Les récits d'usagers peuvent révéler un obstacle concret.", "Quelques récits ne représentent pas automatiquement tous les usagers."],
              action: "Identifier le service responsable et recueillir quelques expériences avec consentement.",
              measure: "Une réponse écrite explique les voies d'accès ou annonce un examen du problème.",
              result: "Le service a confirmé un accueil téléphonique, mais son accès reste peu visible.",
              support: "Des usagers volontaires et une association d'accès aux droits.",
              backup: "Si le canal public est flou, demander d'abord une orientation au service d'accueil.",
              control: "Documenter l'obstacle et demander une réponse précise.",
              outside: "La règle, les moyens et la décision du service public.",
            },
            tool: ["Parcours réel des usagers", "Je distingue les besoins des usagers de mes suppositions et j'observe l'ensemble de leur démarche, y compris les moments d'abandon.", "#ref-28"],
          },
          environment: {
            label: "Environnement et santé collective",
            description: "Une nuisance ou exposition qui touche un groupe.",
            focus: "Quels faits sont connus, qu'est-ce qui reste incertain et qui est exposé ?",
            caution: "Un témoignage de nuisance ne suffit pas à établir sa cause ou un risque sanitaire ; une expertise compétente peut être nécessaire.",
            prompts: ["Quel phénomène est observé, où, quand et par qui ?", "Quelle vérification ou décision publique est demandée ?", "Quelles données et incertitudes faut-il signaler honnêtement ?"],
            examples: {
              situation: "Des riverains signalent régulièrement une odeur près d'une école, sans information publique sur sa source.",
              goal: "Obtenir une vérification par l'autorité compétente et une information compréhensible aux riverains.",
              obstacle: "La source de l'odeur et les mesures déjà réalisées sont inconnues.",
              ideas: ["Consigner dates et lieux des observations sans données personnelles inutiles.", "Chercher les données publiques disponibles.", "Demander à l'autorité compétente quelle vérification est prévue."],
              comparison: ["Des observations datées peuvent préciser la demande.", "Elles ne prouvent pas la cause ni l'effet sur la santé."],
              action: "Identifier l'autorité compétente et lui demander les vérifications existantes.",
              measure: "Une réponse précise les données disponibles et les suites envisagées.",
              result: "Une mesure est annoncée ; sa date et la façon de communiquer le résultat restent à confirmer.",
              support: "Des riverains volontaires et une association compétente.",
              backup: "Si l'autorité est inconnue, demander une orientation à la collectivité.",
              control: "Documenter les observations et formuler une demande prudente.",
              outside: "L'expertise, le contrôle et la décision des autorités.",
            },
            tool: ["Faits, hypothèses et effets possibles", "Je distingue les observations des causes supposées, repère les personnes concernées et demande une vérification adaptée. L'évaluation d'une exposition relève de professionnels compétents.", "#ref-32"],
          },
          decision: {
            label: "Règle, budget ou décision publique",
            description: "Une décision collective peut encore être discutée.",
            focus: "Quelle décision précise peut changer, et quelle influence les participants auront-ils ?",
            caution: "Je n'invite pas des personnes à participer sans expliquer ce qui peut réellement être décidé et comment un retour leur sera fait.",
            prompts: ["Quelle décision est en jeu et à quelle date ?", "Quel changement ou quelle réponse les personnes concernées souhaitent-elles ?", "Qui décide, qui manque au débat et quelles contraintes sont connues ?"],
            examples: {
              situation: "La commune prépare le budget d'un nouvel équipement, mais les usages souhaités par les habitants ne sont pas clairs.",
              goal: "Faire connaître les besoins des habitants avant la décision budgétaire.",
              obstacle: "Nous ne savons pas quelle part du projet peut encore changer ni comment les avis seront utilisés.",
              ideas: ["Demander à la commune quelles décisions restent ouvertes.", "Consulter des habitants volontaires de profils variés.", "Présenter les besoins et les désaccords avant l'arbitrage."],
              comparison: ["Une consultation peut éclairer des usages oubliés.", "Elle serait trompeuse si le budget et les choix sont déjà entièrement fixés."],
              action: "Demander à l'autorité quelles options sont réellement ouvertes à la participation.",
              measure: "La portée de la participation et la date du retour aux habitants sont annoncées.",
              result: "La commune a précisé deux choix ouverts ; le retour aux participants reste à organiser.",
              support: "Des habitants volontaires et l'instance responsable du projet.",
              backup: "Si aucune décision n'est ouverte, demander plutôt une information publique honnête.",
              control: "Poser une question précise et organiser une expression volontaire.",
              outside: "Le vote budgétaire et l'arbitrage final.",
            },
            tool: ["Participation avec influence réelle", "Je vérifie la place possible des citoyens dans la décision, annonce les limites et prévois un retour sur l'usage de leurs contributions.", "#ref-25"],
          },
          other: {
            label: "Autre problème collectif ou politique",
            description: "Un enjeu public qui ne ressemble pas aux exemples proposés.",
            focus: "Qui est concerné, quelle décision est recherchée et qui en a la compétence ?",
            caution: "Je distingue ce que le groupe demande de ce que l'autorité peut réellement décider.",
            prompts: ["Quels faits publics décrivent le problème et qui est touché ?", "Quelle réponse ou décision identifiable est demandée ?", "Quelles informations, personnes ou compétences manquent encore ?"],
            examples: {
              situation: "Un équipement collectif est peu utilisé et les habitants ne savent pas pourquoi ses horaires ont changé.",
              goal: "Obtenir les raisons du changement d'horaires et discuter une adaptation possible.",
              obstacle: "Le responsable de la décision et les contraintes de fonctionnement ne sont pas connus.",
              ideas: ["Consulter les informations publiques disponibles.", "Demander aux usagers volontaires quels horaires leur sont utiles.", "Adresser une question précise à l'autorité compétente."],
              comparison: ["Une question documentée peut clarifier la décision.", "Une modification peut dépendre de moyens non disponibles."],
              action: "Identifier l'autorité compétente et demander les motifs des horaires actuels.",
              measure: "Une réponse documentée explique la décision ou propose un échange.",
              result: "La raison du changement a été communiquée ; une adaptation reste à discuter.",
              support: "Des usagers volontaires et une association locale.",
              backup: "Si le décideur est inconnu, demander une orientation à la collectivité.",
              control: "Réunir les faits et formuler une demande avec les volontaires.",
              outside: "Le pouvoir de décision et les ressources de l'autorité.",
            },
            tool: ["Problème, décision et retour", "Je formule une question publique précise, vérifie qui peut agir et prévois d'informer les personnes participantes de la réponse.", "#ref-25"],
          },
        },
      };
