      // The same state shape and print sheet serve four distinct journeys.
      // Copy, prompts, examples and tools change with the scale selected in step 1.
      const workflows = {
        personal: {
          steps: ["Mon contexte", "Un but précis", "Ma liste de pistes", "Comparer les options", "Un premier pas", "Après l’essai"],
          titles: ["Mon contexte", "Quel est mon problème ?", "Quelles solutions puis-je noter ?", "Quelle option me convient ?", "Quel sera mon premier pas ?", "Après l’essai, où en suis-je ?"],
          leads: ["", "Une situation, un but, un obstacle. Quelques phrases suffisent.", "Je fais une liste de solutions possibles, même imparfaites. Je les comparerai ensuite.", "Je choisis une piste faisable, sûre et adaptée à ce qui compte pour moi.", "Je prévois une petite action, un moment et un signe de progrès.", "Je fais le point après l’action et j’ajuste si besoin."],
          fields: ["Ce qui se passe", "Racontez un fait précis, sans nom ni adresse.", "Le petit changement que je souhaite", "Qu’aimeriez-vous voir changer concrètement ?", "Ce qui me bloque", "Quel est le principal obstacle ?"],
          contextCheckTitle: "Ce qui compte pour moi ici (facultatif)",
          contextCheck: "La langue utilisée, les attentes de mon entourage ou une règle qui me bloque changent-elles mes choix ? Je peux aussi noter si je suis mis à l’écart ou traité injustement. Je retiens ce qui compte pour moi.",
          idea: "Pour allonger ma liste, je peux demander des idées à des personnes de confiance, chercher sur des sites fiables ou consulter un spécialiste si nécessaire et accessible. Je vérifie les informations importantes avant de choisir.",
          compare: "Laquelle respecte mes besoins, demande une énergie acceptable et peut être essayée sans me mettre en danger ?",
          action: ["Ma première action", "Choisissez une action assez petite pour commencer.", "Comment saurai-je que j’ai avancé ?", "Un petit signe concret suffit."],
          tools: [
            null,
            ["Faits · but · obstacle", "Décrire une scène concrète évite de confondre une difficulté avec un jugement global sur soi.", "#ref-3"],
            ["Faire une liste de pistes", "Je note plusieurs solutions sans les juger tout de suite. Une information, une demande d’aide ou une petite action peuvent être des pistes différentes.", "#ref-3"],
            ["Comparer sans viser la perfection", "Regarder la faisabilité, les risques et les ressources disponibles.", "#ref-3"],
            ["Si… alors…", "Prévoir quand commencer et quoi faire si un obstacle apparaît.", "#ref-4"],
          ],
        },
        shared: {
          steps: ["La relation", "Comprendre chacun", "Des pistes à discuter", "Un choix respectueux", "Proposer avec accord", "Ce qui a changé"],
          titles: ["Mon contexte", "Qu’est-ce qui compte pour chacun ?", "Quelles pistes puis-je envisager ?", "Quelle piste respecte nos limites ?", "Quel pas puis-je proposer sans imposer ?", "Qu’est-ce qui a changé ?"],
          leads: ["", "Je distingue les faits, mon besoin et ce que je sais réellement du besoin de l’autre.", "Je fais une liste de propositions possibles, sans supposer l’accord de l’autre personne. Je les comparerai ensuite.", "Je compare les effets pour chacun, les souhaits exprimés et la liberté réelle de refuser.", "Je propose un échange ou un essai seulement si chacun peut refuser librement. Je peux aussi choisir un autre soutien.", "Je note ce qui s’est passé, les désaccords restants et ce qui doit changer."],
          fields: ["Ce qui s’est passé entre nous", "Décrivez des faits observables, sans attribuer d’intention à l’autre.", "Ce que je souhaite pour la relation", "Quel changement serait acceptable pour moi et à discuter avec l’autre ?", "Ce qui empêche l’accord", "Quelles informations, limites ou contraintes restent à clarifier ?"],
          contextCheckTitle: "Nos points de vue ou nos mots diffèrent-ils ? (facultatif)",
          contextCheck: "Nous pouvons comprendre la situation différemment. Qu’ai-je vraiment entendu de l’autre personne ? La langue, une règle non écrite ou le pouvoir de décider pour l’autre rendent-ils la discussion difficile ? Je ne propose un échange que si c’est sûr.",
          examples: ["Nous avons discuté deux fois d’une tâche, mais nous n’avons pas clarifié qui ferait quoi.", "Nous voulons choisir une répartition que chacun peut accepter.", "Nous ne connaissons pas encore les contraintes de l’autre."],
          idea: "Je garde une place pour les idées de l’autre personne si l’échange est sûr. Je peux aussi chercher des informations fiables ou demander conseil à un tiers compétent si nécessaire et accessible, sans raconter sa situation sans son accord.",
          ideas: ["Demander un moment pour écouter le point de vue de chacun.", "Proposer deux façons de répartir la tâche, à discuter ensemble.", "Demander l’aide d’un tiers sûr si les deux personnes le souhaitent."],
          comparison: ["Chacun peut exprimer son besoin et ses limites.", "L’autre personne peut refuser ou proposer autre chose."],
          compare: "La personne peut-elle dire non librement ? Est-ce un essai juste pour les deux ?",
          action: ["Ma proposition de premier pas", "Formulez une invitation, pas une décision prise à la place de l’autre.", "Comment saurons-nous si cela aide ?", "Définissez un signe que chacun pourra observer."],
          actionExamples: ["Proposer un échange de quinze minutes pour écouter nos contraintes.", "Nous avons nommé une répartition qui convient à chacun, ou les désaccords restants."],
          tools: [null, ["Écoute et reformulation", "Demander le point de vue de l’autre, puis reformuler et vérifier ce que l’on a compris.", "#ref-5"], ["Options co-construites", "Inviter l’autre personne à proposer ses propres pistes avant de choisir.", "#ref-5"], ["Accord libre", "Un compromis n’est utile que si chacun peut exprimer ses limites sans peur.", "#ref-6"], ["Essai réversible", "Prévoir quand demander à chacun si l’accord fonctionne.", "#ref-4"]],
        },
        organization: {
          steps: ["Le système", "Définir le problème", "Des changements possibles", "Choisir un test", "Tester à petite échelle", "Mesurer et ajuster"],
          titles: ["Mon contexte", "Quel problème le système produit-il ?", "Quels changements pourrions-nous envisager ?", "Quel test est faisable et équitable ?", "Comment tester à petite échelle ?", "Qu’avons-nous appris du test ?"],
          leads: ["", "Je décris les faits, le résultat recherché et les contraintes de l’organisation.", "Je liste plusieurs changements possibles dans le travail, les ressources ou la coordination. Je les comparerai ensuite.", "Je considère les effets du test, qui décide et qui pourrait rester à l’écart.", "Je définis un petit test, un responsable et un indicateur simple.", "Je compare le résultat attendu aux observations et je décide d’ajuster ou d’arrêter."],
          fields: ["Le problème observé dans l’organisation", "Précisez où, quand et pour qui le problème apparaît.", "Le résultat que l’équipe cherche", "Qu’est-ce qui devrait changer pour les personnes concernées ?", "Les contraintes ou causes possibles", "Distinguez les faits vérifiés des hypothèses à examiner."],
          contextCheckTitle: "Qui risque de ne pas être entendu ? (facultatif)",
          contextCheck: "Qui comprend les consignes et qui manque dans la discussion ? La langue des consignes, un horaire, une règle non écrite ou une mise à l’écart empêchent-ils certaines personnes d’agir ?",
          examples: ["Dans l’équipe, trois demandes urgentes arrivent le même jour sans règle de priorité partagée.", "L’équipe saura quelle demande traiter en premier et qui décide.", "Les priorités sont fixées par plusieurs responsables et ne sont pas visibles par tous."],
          idea: "Pour allonger la liste, je peux demander leurs idées aux personnes qui font le travail, chercher des exemples fiables en ligne ou consulter un spécialiste du sujet si nécessaire et accessible.",
          ideas: ["Cartographier une étape du travail avec les personnes concernées.", "Tester une nouvelle coordination sur une seule situation.", "Demander une ressource ou une décision au responsable compétent."],
          comparison: ["Un petit test permet d’observer si le changement aide.", "Un test local peut ne pas refléter tous les cas et demander du temps."],
          compare: "Le test est-il sûr, mesurable et acceptable pour les personnes concernées ?",
          action: ["Le petit test à organiser", "Précisez qui doit valider, où et quand le test aura lieu.", "Quel signe concret observer ?", "Choisissez un indicateur simple, utile et sans données personnelles inutiles."],
          actionExamples: ["Proposer au responsable un test de priorisation pour la prochaine réunion d’équipe.", "Les trois demandes ont un ordre de priorité connu par l’équipe."],
          tools: [null, ["Définir un objectif", "Le modèle d’amélioration commence par ce que l’équipe cherche à accomplir.", "#ref-22"], ["Idées avec l’équipe", "Les personnes concernées par le processus peuvent révéler des contraintes invisibles de l’extérieur.", "#ref-22"], ["Choisir une mesure", "Préciser comment savoir si le changement améliore la situation et pour qui.", "#ref-22"], ["Cycle tester · observer · ajuster", "Un test à petite échelle permet d’apprendre avant une mise en œuvre plus large.", "#ref-22"]],
        },
        public: {
          steps: ["Le sujet public", "Définir l’enjeu", "Des démarches possibles", "Choisir une voie", "Une démarche civique", "Suivre la réponse"],
          titles: ["Mon contexte", "Qui est touché et quelle décision manque ?", "Quelles démarches pourrions-nous envisager ?", "Quelle démarche est légitime et faisable ?", "Quelle première démarche pouvons-nous faire ?", "Quelle réponse avons-nous obtenue ?"],
          leads: ["", "Je distingue les témoignages, les données, les hypothèses et la décision publique visée.", "Je liste plusieurs démarches possibles avec les personnes concernées. Nous les comparerons ensuite.", "Je considère les effets, qui décide et qui peut réellement participer.", "Je prépare une demande vérifiable, avec les personnes qui souhaitent participer.", "Je documente la réponse, les limites et la prochaine décision collective."],
          fields: ["Le problème public observé", "Décrivez des faits vérifiables et évitez les données personnelles.", "Le changement public recherché", "Quelle décision, règle, ressource ou pratique devrait évoluer ?", "Ce qui manque pour agir", "Qui décide ? Quelles preuves, alliances ou ressources manquent ?"],
          contextCheckTitle: "Qui manque dans ce constat ? (facultatif)",
          contextCheck: "Qui a pu décrire le problème, et qui manque ? La langue, le format de consultation ou l’accès aux services empêchent-ils certaines personnes de participer ?",
          examples: ["Plusieurs habitants signalent que l’arrêt de bus est difficile d’accès ; les informations publiques ne précisent pas les travaux prévus.", "Obtenir une réponse sur les aménagements possibles et leur calendrier.", "Nous ne savons pas encore quel service décide ni quelles personnes souhaitent participer."],
          idea: "Pour allonger la liste, nous pouvons demander des idées aux personnes concernées, chercher des informations publiques fiables en ligne ou consulter un spécialiste du sujet si nécessaire et accessible.",
          ideas: ["Demander aux personnes concernées si elles souhaitent participer et comment.", "Identifier l’autorité compétente et les informations publiques existantes.", "Préparer une demande collective avec un objectif et des faits vérifiables."],
          comparison: ["La démarche peut rendre le problème visible et obtenir une réponse.", "Une réponse ne garantit ni financement ni changement immédiat."],
          compare: "Les personnes concernées ont-elles réellement voix au chapitre ? La démarche respecte-t-elle leurs choix et leurs risques ?",
          action: ["La première démarche collective", "Précisez qui participe volontairement et à quelle autorité s’adresser.", "Quel signe de progrès public ?", "Par exemple : un rendez-vous, une réponse écrite ou une décision documentée."],
          actionExamples: ["Demander aux personnes intéressées si elles souhaitent coécrire une question au service compétent.", "Le service a répondu par écrit ou indiqué une date de rendez-vous."],
          tools: [null, ["Problème et personnes concernées", "Identifier le contexte, les groupes touchés et les effets potentiellement inégaux.", "#ref-23"], ["Carte des acteurs", "Repérer qui décide, qui met en œuvre et qui subit les conséquences.", "#ref-24"], ["Effets attendus et effets indésirables", "Comparer les options avec leurs coûts, leurs effets et la possibilité d’un suivi public.", "#ref-24"], ["Demande vérifiable", "Relier la démarche, la décision attendue et un indicateur de réponse.", "#ref-23"]],
        },
      };
