      // The same state shape and print sheet serve four distinct journeys.
      // Copy, prompts, examples and tools change with the scale selected in step 1.
      const workflows = {
        personal: {
          steps: ["Mon contexte", "Un but précis", "Plusieurs pistes", "Comparer les options", "Un premier pas", "Après l’essai"],
          titles: ["Mon contexte", "Quel est mon problème ?", "Quelles pistes puis-je essayer ?", "Quelle option me convient ?", "Quel sera mon premier pas ?", "Après l’essai, où en suis-je ?"],
          leads: ["", "Une situation, un but, un obstacle. Quelques phrases suffisent.", "Je note des idées, même imparfaites. Une seule suffit pour commencer.", "Je choisis une piste faisable et sûre pour moi.", "Je prévois une petite action, un moment et un signe de progrès.", "Je fais le point après l’action et j’ajuste si besoin."],
          fields: ["Ce qui se passe", "Racontez un fait précis, sans nom ni adresse.", "Le petit changement que je souhaite", "Qu’aimeriez-vous voir changer concrètement ?", "Ce qui me bloque", "Quel est le principal obstacle ?"],
          idea: "Faire autrement, demander de l’aide ou chercher une information : tout peut être une piste.",
          compare: "Laquelle respecte mes besoins, demande une énergie acceptable et peut être essayée sans me mettre en danger ?",
          action: ["Ma première action", "Choisissez une action assez petite pour commencer.", "Comment saurai-je que j’ai avancé ?", "Un petit signe concret suffit."],
          tools: [
            null,
            ["Faits · but · obstacle", "Décrire une scène concrète évite de confondre une difficulté avec un jugement global sur soi.", "#ref-3"],
            ["Chercher plusieurs pistes", "Une information, une demande d’aide ou une petite action peuvent être des pistes différentes.", "#ref-3"],
            ["Comparer sans viser la perfection", "Regarder la faisabilité, les risques et les ressources disponibles.", "#ref-3"],
            ["Si… alors…", "Prévoir quand commencer et quoi faire si un obstacle apparaît.", "#ref-4"],
          ],
        },
        shared: {
          steps: ["La relation", "Comprendre chacun", "Des pistes à proposer", "Un choix respectueux", "Proposer avec accord", "Ce qui a changé"],
          titles: ["Mon contexte", "Qu’est-ce qui compte pour chacun ?", "Quelles pistes puis-je envisager ?", "Quelle piste respecte nos limites ?", "Quel pas puis-je proposer sans imposer ?", "Qu’est-ce qui a changé ?"],
          leads: ["", "Je distingue les faits, mon besoin et ce que je sais réellement du besoin de l’autre.", "Je prépare des propositions, sans supposer l’accord de l’autre personne.", "Je compare les effets pour chacun et la liberté réelle de refuser.", "Je propose un échange ou un essai seulement si chacun peut refuser librement. Je peux aussi choisir un autre soutien.", "Je note ce qui s’est passé, les désaccords restants et ce qui doit changer."],
          fields: ["Ce qui s’est passé entre nous", "Décrivez des faits observables, sans attribuer d’intention à l’autre.", "Ce que je souhaite pour la relation", "Quel changement serait acceptable pour moi et à discuter avec l’autre ?", "Ce qui empêche l’accord", "Quelles informations, limites ou contraintes restent à clarifier ?"],
          examples: ["Nous avons discuté deux fois d’une tâche, mais nous n’avons pas clarifié qui ferait quoi.", "Nous voulons choisir une répartition que chacun peut accepter.", "Nous ne connaissons pas encore les contraintes de l’autre."],
          idea: "Préparer plusieurs propositions et garder de la place pour les idées de l’autre personne.",
          ideas: ["Demander un moment pour écouter le point de vue de chacun.", "Proposer deux façons de répartir la tâche, à discuter ensemble.", "Demander l’aide d’un tiers sûr si les deux personnes le souhaitent."],
          comparison: ["Chacun peut exprimer son besoin et ses limites.", "L’autre personne peut refuser ou proposer autre chose."],
          compare: "La personne peut-elle dire non librement ? Est-ce un essai juste pour les deux ?",
          action: ["Ma proposition de premier pas", "Formulez une invitation, pas une décision prise à la place de l’autre.", "Comment saurons-nous si cela aide ?", "Définissez un signe que chacun pourra observer."],
          actionExamples: ["Proposer un échange de quinze minutes pour écouter nos contraintes.", "Nous avons nommé une répartition qui convient à chacun, ou les désaccords restants."],
          tools: [null, ["Écoute et reformulation", "Demander le point de vue de l’autre, puis reformuler et vérifier ce que l’on a compris.", "#ref-5"], ["Options co-construites", "Inviter l’autre personne à proposer ses propres pistes avant de choisir.", "#ref-5"], ["Accord libre", "Un compromis n’est utile que si chacun peut exprimer ses limites sans peur.", "#ref-6"], ["Essai réversible", "Prévoir quand demander à chacun si l’accord fonctionne.", "#ref-4"]],
        },
        organization: {
          steps: ["Le système", "Définir le problème", "Changements possibles", "Choisir un test", "Tester à petite échelle", "Mesurer et ajuster"],
          titles: ["Mon contexte", "Quel problème le système produit-il ?", "Quels changements pourrions-nous tester ?", "Quel test est faisable et équitable ?", "Comment tester à petite échelle ?", "Qu’avons-nous appris du test ?"],
          leads: ["", "Je décris les faits, le résultat recherché et les contraintes de l’organisation.", "Je cherche des changements de processus, de ressources ou de coordination.", "Je considère les bénéfices, les effets indésirables et qui devra décider.", "Je définis un petit test, un responsable et un indicateur simple.", "Je compare le résultat attendu aux observations et je décide d’ajuster ou d’arrêter."],
          fields: ["Le problème observé dans l’organisation", "Précisez où, quand et pour qui le problème apparaît.", "Le résultat que l’équipe cherche", "Qu’est-ce qui devrait changer pour les personnes concernées ?", "Les contraintes ou causes possibles", "Distinguez les faits vérifiés des hypothèses à examiner."],
          examples: ["Dans l’équipe, trois demandes urgentes arrivent le même jour sans règle de priorité partagée.", "L’équipe saura quelle demande traiter en premier et qui décide.", "Les priorités sont fixées par plusieurs responsables et ne sont pas visibles par tous."],
          idea: "Chercher des changements de processus, de coordination ou de ressources ; inclure les personnes qui font le travail.",
          ideas: ["Cartographier une étape du travail avec les personnes concernées.", "Tester une nouvelle coordination sur une seule situation.", "Demander une ressource ou une décision au responsable compétent."],
          comparison: ["Un petit test permet d’observer si le changement aide.", "Un test local peut ne pas refléter tous les cas et demander du temps."],
          compare: "Le test est-il sûr, mesurable et acceptable pour les personnes concernées ?",
          action: ["Le petit test à organiser", "Précisez qui doit valider, où et quand le test aura lieu.", "Quel signe concret observer ?", "Choisissez un indicateur simple, utile et sans données personnelles inutiles."],
          actionExamples: ["Proposer au responsable un test de priorisation pour la prochaine réunion d’équipe.", "Les trois demandes ont un ordre de priorité connu par l’équipe."],
          tools: [null, ["Définir un objectif", "Le modèle d’amélioration commence par ce que l’équipe cherche à accomplir.", "#ref-22"], ["Idées avec l’équipe", "Les personnes concernées par le processus peuvent révéler des contraintes invisibles de l’extérieur.", "#ref-22"], ["Choisir une mesure", "Préciser comment savoir si le changement améliore la situation et pour qui.", "#ref-22"], ["Cycle tester · observer · ajuster", "Un test à petite échelle permet d’apprendre avant une mise en œuvre plus large.", "#ref-22"]],
        },
        public: {
          steps: ["Le sujet public", "Définir l’enjeu", "Leviers collectifs", "Choisir une voie", "Une démarche civique", "Suivre la réponse"],
          titles: ["Mon contexte", "Qui est touché et quelle décision manque ?", "Quels leviers collectifs existent ?", "Quelle démarche est légitime et faisable ?", "Quelle première démarche pouvons-nous faire ?", "Quelle réponse avons-nous obtenue ?"],
          leads: ["", "Je distingue les témoignages, les données, les hypothèses et la décision publique visée.", "J’explore les démarches accessibles aux personnes concernées.", "Je considère les effets, les ressources, le calendrier et qui décide.", "Je prépare une demande vérifiable, avec les personnes qui souhaitent participer.", "Je documente la réponse, les limites et la prochaine décision collective."],
          fields: ["Le problème public observé", "Décrivez des faits vérifiables et évitez les données personnelles.", "Le changement public recherché", "Quelle décision, règle, ressource ou pratique devrait évoluer ?", "Ce qui manque pour agir", "Qui décide ? Quelles preuves, alliances ou ressources manquent ?"],
          examples: ["Plusieurs habitants signalent que l’arrêt de bus est difficile d’accès ; les informations publiques ne précisent pas les travaux prévus.", "Obtenir une réponse sur les aménagements possibles et leur calendrier.", "Nous ne savons pas encore quel service décide ni quelles personnes souhaitent participer."],
          idea: "Explorer information publique, consultation, association, demande argumentée ou dialogue avec le décideur compétent.",
          ideas: ["Demander aux personnes concernées si elles souhaitent participer et comment.", "Identifier l’autorité compétente et les informations publiques existantes.", "Préparer une demande collective avec un objectif et des faits vérifiables."],
          comparison: ["La démarche peut rendre le problème visible et obtenir une réponse.", "Une réponse ne garantit ni financement ni changement immédiat."],
          compare: "Les personnes concernées ont-elles réellement voix au chapitre ? La démarche respecte-t-elle leurs choix et leurs risques ?",
          action: ["La première démarche collective", "Précisez qui participe volontairement et à quelle autorité s’adresser.", "Quel signe de progrès public ?", "Par exemple : un rendez-vous, une réponse écrite ou une décision documentée."],
          actionExamples: ["Demander aux personnes intéressées si elles souhaitent coécrire une question au service compétent.", "Le service a répondu par écrit ou indiqué une date de rendez-vous."],
          tools: [null, ["Problème et personnes concernées", "Identifier le contexte, les groupes touchés et les effets potentiellement inégaux.", "#ref-23"], ["Carte des acteurs", "Repérer qui décide, qui met en œuvre et qui subit les conséquences.", "#ref-24"], ["Effets attendus et effets indésirables", "Comparer les options avec leurs coûts, leurs effets et la possibilité d’un suivi public.", "#ref-24"], ["Demande vérifiable", "Relier la démarche, la décision attendue et un indicateur de réponse.", "#ref-23"]],
        },
      };
